services:
  db:
    image: mysql:8.0
    container_name: ${DATABASE_CONTAINER_NAME}
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - "127.0.0.1:${DATABASE_PORT}:3306"
    volumes:
      - db:/var/lib/mysql

  redis:
    image: bitnami/redis
    container_name: ${REDIS_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "127.0.0.1:${REDIS_PORT}:6379"
    volumes:
      - redis:/var/lib/redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

volumes:
  db:
  redis:
