version: '3.8'

volumes:
    mysql.data:

services:
    mysql:
        image: mysql:8.0
        container_name: ${COMPOSE_PROJECT_NAME}.mysql.docker
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${DATABASE_USERNAME}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
        volumes:
            - mysql.data:/var/lib/mysql
        ports:
            - 127.0.0.1:${DATABASE_PORT}:3306
        networks:
            - network

networks:
    network:
        driver: bridge
